spring:
  application:
    name: growe-backend
  mvc:
    thow-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/growe_db}
    username: ${DB_USERNAME:growe_dev}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  public:
    key: ${JWT_PUBLIC_KEY:file:certs/public.pem}
  private:
    key: ${JWT_PRIVATE_KEY:file:certs/private_pkcs8.pem}

app:
  # Set to true in development/staging, false in production
  include-error-details: ${INCLUDE_ERROR_DETAILS:false}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

groq:
  api:
    url: ${GROQ_API_URL}
    key: ${GROQ_API_KEY}
    model: ${GROQ_API_MODEL}