spring:
  application:
    name: growe-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/growe_db}
    username: ${DB_USERNAME:growe_dev}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}

jwt:
  public:
    key: ${JWT_PUBLIC_KEY:file:certs/public.pem}
  private:
    key: ${JWT_PRIVATE_KEY:file:certs/private_pkcs8.pem}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
  api-docs:
    path: /v3/api-docs